use serde_json::{Value, json};

type ToolSpec = (
    &'static str,
    &'static str,
    &'static [(&'static str, &'static str)],
    &'static [(&'static str, &'static str)],
    bool,
    bool,
);

pub fn append(tools: &mut Vec<Value>) {
    let specs: &[ToolSpec] = &[
        (
            "structured_data_query",
            "Read JSON, TOML, YAML, XML or CSV and select a value using an RFC 6901 JSON Pointer.",
            &[("path", "string")],
            &[("format", "string"), ("pointer", "string")],
            true,
            true,
        ),
        (
            "structured_data_diff",
            "Compare two JSON, TOML, YAML, XML or CSV documents and report bounded pointer-addressed changes.",
            &[("leftPath", "string"), ("rightPath", "string")],
            &[
                ("format", "string"),
                ("pointer", "string"),
                ("limit", "integerNumber"),
            ],
            true,
            true,
        ),
        (
            "dependency_inventory",
            "Inventory direct dependencies and available lock or local install versions in Cargo, Python, npm and NuGet projects.",
            &[("root", "string")],
            &[("maxDepth", "integerNumber"), ("limit", "integerNumber")],
            true,
            true,
        ),
        (
            "workspace_scan",
            "Discover repositories and build manifests beneath a directory without entering generated output directories.",
            &[("root", "string")],
            &[("maxDepth", "integerNumber"), ("limit", "integerNumber")],
            true,
            true,
        ),
        (
            "repo_status_batch",
            "Summarize branch, HEAD, changed files and linked worktrees for repositories beneath a directory.",
            &[("root", "string")],
            &[("maxDepth", "integerNumber"), ("limit", "integerNumber")],
            true,
            true,
        ),
        (
            "command_pipeline",
            "Run up to 32 explicit executable steps in order, capturing bounded output and stopping at failure by default.",
            &[("steps", "pipelineSteps")],
            &[("continueOnError", "boolean")],
            false,
            false,
        ),
        (
            "environment_snapshot",
            "Capture OS identity, selected environment variables and bounded executable version probes.",
            &[],
            &[
                ("executables", "string[]"),
                ("variables", "string[]"),
                ("versionArguments", "string[]"),
            ],
            true,
            true,
        ),
        (
            "file_watch",
            "Wait for added, removed or metadata-modified files beneath a directory; return bounded change events.",
            &[("root", "string")],
            &[
                ("recursive", "boolean"),
                ("timeoutMs", "integerNumber"),
                ("intervalMs", "integerNumber"),
                ("limit", "integerNumber"),
            ],
            true,
            true,
        ),
        (
            "process_start",
            "Start a process with separate executable and argument array; retain bounded output for process_output.",
            &[("executable", "string")],
            &[
                ("arguments", "string[]"),
                ("cwd", "string"),
                ("env", "stringMap"),
            ],
            false,
            false,
        ),
        (
            "process_run",
            "Run an executable and return exit status and bounded stdout/stderr; time out and kill if requested.",
            &[("executable", "string")],
            &[
                ("arguments", "string[]"),
                ("cwd", "string"),
                ("env", "stringMap"),
                ("timeoutMs", "integerNumber"),
                ("maxOutputBytes", "integerNumber"),
            ],
            false,
            false,
        ),
        (
            "process_get",
            "Inspect a PID, including memory, CPU sampled over an interval, command line and I/O counters.",
            &[("pid", "integerNumber")],
            &[("sampleMs", "integerNumber")],
            true,
            true,
        ),
        (
            "process_list",
            "List processes, optionally filtering by case-insensitive name substring.",
            &[],
            &[("name", "string"), ("limit", "integerNumber")],
            true,
            true,
        ),
        (
            "process_tree",
            "Return a process and its descendants from a PID snapshot.",
            &[("pid", "integerNumber")],
            &[],
            true,
            true,
        ),
        (
            "process_wait",
            "Wait for a managed child or for an arbitrary PID to disappear.",
            &[("pid", "integerNumber")],
            &[("timeoutMs", "integerNumber")],
            true,
            true,
        ),
        (
            "process_output",
            "Read bounded stdout/stderr captured from a process started by this server; release after exit to free its slot.",
            &[("pid", "integerNumber")],
            &[
                ("release", "boolean"),
                ("stdoutOffset", "integerNumber"),
                ("stderrOffset", "integerNumber"),
            ],
            false,
            false,
        ),
        (
            "process_stop",
            "Stop a PID, optionally including descendants; force defaults to true.",
            &[("pid", "integerNumber")],
            &[
                ("tree", "boolean"),
                ("force", "boolean"),
                ("expectedStartTimeUnix", "integerNumber"),
            ],
            false,
            false,
        ),
        (
            "process_modules",
            "List loaded modules of a Windows process.",
            &[("pid", "integerNumber")],
            &[],
            true,
            true,
        ),
        (
            "file_find",
            "Find files by basename wildcard under a root directory.",
            &[("root", "string")],
            &[
                ("pattern", "string"),
                ("recursive", "boolean"),
                ("limit", "integerNumber"),
            ],
            true,
            true,
        ),
        (
            "text_search",
            "Search UTF-8 files for literal or regex text and return line/column matches.",
            &[("root", "string"), ("pattern", "string")],
            &[
                ("regex", "boolean"),
                ("caseSensitive", "boolean"),
                ("limit", "integerNumber"),
            ],
            true,
            true,
        ),
        (
            "file_stat",
            "Return file type, size and modification time.",
            &[("path", "string")],
            &[],
            true,
            true,
        ),
        (
            "file_hash",
            "Stream a file and compute SHA-256 or SHA-512.",
            &[("path", "string")],
            &[("algorithm", "string")],
            true,
            true,
        ),
        (
            "file_read_range",
            "Read a bounded byte range as UTF-8 or hexadecimal.",
            &[
                ("path", "string"),
                ("offset", "integerNumber"),
                ("length", "integerNumber"),
            ],
            &[("encoding", "string")],
            true,
            true,
        ),
        (
            "file_write_atomic",
            "Write UTF-8 content via a temporary file and atomic persist.",
            &[("path", "string"), ("content", "string")],
            &[("overwrite", "boolean")],
            false,
            false,
        ),
        (
            "file_copy_move",
            "Copy or move a file or directory to a destination.",
            &[
                ("source", "string"),
                ("destination", "string"),
                ("operation", "string"),
            ],
            &[("overwrite", "boolean")],
            false,
            false,
        ),
        (
            "port_owner",
            "Find Windows TCP or UDP endpoints and owning PIDs for a local port.",
            &[("port", "integerNumber")],
            &[("protocol", "string")],
            true,
            true,
        ),
        (
            "service_get",
            "Read Windows service status, startup mode and process ID.",
            &[("name", "string")],
            &[],
            true,
            true,
        ),
        (
            "service_control",
            "Start, stop or restart a Windows service.",
            &[("name", "string"), ("action", "string")],
            &[],
            false,
            false,
        ),
        (
            "eventlog_query",
            "Read recent Windows event log entries.",
            &[("logName", "string")],
            &[("maxEvents", "integerNumber")],
            true,
            true,
        ),
        (
            "registry_read",
            "Read one Windows registry property using a literal registry path.",
            &[("path", "string"), ("property", "string")],
            &[],
            true,
            true,
        ),
        (
            "environment_get",
            "Read one environment variable from process, user or machine scope.",
            &[("name", "string")],
            &[("scope", "string")],
            true,
            true,
        ),
        (
            "system_info",
            "Read OS, CPU and memory information.",
            &[],
            &[],
            true,
            true,
        ),
        (
            "archive_create",
            "Create a ZIP archive from file and directory paths.",
            &[("archive", "string"), ("paths", "string[]")],
            &[("overwrite", "boolean")],
            false,
            false,
        ),
        (
            "archive_extract",
            "Extract a ZIP archive with path traversal protection.",
            &[("archive", "string"), ("destination", "string")],
            &[("overwrite", "boolean")],
            false,
            false,
        ),
        (
            "powershell_run",
            "Run a supplied PowerShell script with timeout and bounded captured output (Windows only).",
            &[("script", "string")],
            &[
                ("timeoutMs", "integerNumber"),
                ("maxOutputBytes", "integerNumber"),
            ],
            false,
            false,
        ),
        (
            "process_input",
            "Write UTF-8 or hex bytes to a managed process stdin and optionally close it.",
            &[("pid", "integerNumber")],
            &[
                ("data", "string"),
                ("encoding", "string"),
                ("close", "boolean"),
            ],
            false,
            false,
        ),
        (
            "wait_for",
            "Wait for a file, process exit, TCP port or HTTP status with a bounded timeout.",
            &[("kind", "string")],
            &[
                ("path", "string"),
                ("pid", "integerNumber"),
                ("host", "string"),
                ("port", "integerNumber"),
                ("url", "string"),
                ("expectedStatus", "integerNumber"),
                ("timeoutMs", "integerNumber"),
                ("intervalMs", "integerNumber"),
            ],
            true,
            true,
        ),
        (
            "file_patch",
            "Atomically replace exact UTF-8 or hex byte sequences with expected match count and optional SHA-256 precondition.",
            &[
                ("path", "string"),
                ("find", "string"),
                ("replace", "string"),
            ],
            &[
                ("mode", "string"),
                ("expectedMatches", "integerNumber"),
                ("expectedSha256", "string"),
            ],
            false,
            false,
        ),
        (
            "http_request",
            "Send a bounded HTTP or HTTPS request and return status, headers and body.",
            &[("url", "string")],
            &[
                ("method", "string"),
                ("headers", "stringMap"),
                ("body", "string"),
                ("timeoutMs", "integerNumber"),
                ("maxBodyBytes", "integerNumber"),
            ],
            false,
            false,
        ),
        (
            "network_probe",
            "Probe a TCP port or verified TLS handshake and report latency and certificate hash.",
            &[("host", "string"), ("port", "integerNumber")],
            &[("protocol", "string"), ("timeoutMs", "integerNumber")],
            true,
            true,
        ),
        (
            "dns_query",
            "Query A, AAAA, CNAME, MX, NS, TXT or SRV records with a bounded timeout.",
            &[("name", "string")],
            &[("recordType", "string"), ("timeoutMs", "integerNumber")],
            true,
            true,
        ),
        (
            "executable_resolve",
            "Resolve an executable by path or PATH and report its architecture, file size and available version metadata.",
            &[("name", "string")],
            &[],
            true,
            true,
        ),
        (
            "directory_manifest",
            "Inventory a directory with optional SHA-256 hashes and a bounded entry count.",
            &[("root", "string")],
            &[("hashFiles", "boolean"), ("limit", "integerNumber")],
            true,
            true,
        ),
        (
            "file_signature",
            "Inspect Authenticode status, signer and version information for a Windows file.",
            &[("path", "string")],
            &[],
            true,
            true,
        ),
        (
            "scheduled_task",
            "List, inspect, run, stop, enable, disable, register or unregister Windows scheduled tasks.",
            &[("operation", "string")],
            &[
                ("name", "string"),
                ("taskPath", "string"),
                ("limit", "integerNumber"),
                ("executable", "string"),
                ("actionArguments", "string"),
                ("trigger", "string"),
                ("at", "string"),
                ("overwrite", "boolean"),
            ],
            false,
            false,
        ),
        (
            "eventlog_follow",
            "Read Windows event log entries after a record ID and return the next cursor.",
            &[("logName", "string")],
            &[
                ("afterRecordId", "integerNumber"),
                ("maxEvents", "integerNumber"),
            ],
            true,
            true,
        ),
        (
            "performance_sample",
            "Sample CPU, memory and network transfer over an interval; include disk capacity.",
            &[],
            &[("sampleMs", "integerNumber")],
            true,
            true,
        ),
        (
            "acl_get",
            "Read a Windows file or directory owner, SDDL and access entries.",
            &[("path", "string")],
            &[],
            true,
            true,
        ),
    ];
    for &(name, description, required, optional, read_only, idempotent) in specs {
        crate::catalog::add_extra(tools, name, description, required, optional);
        let may_execute = matches!(name, "environment_snapshot");
        tools.last_mut().unwrap()["annotations"] = json!({
            "readOnlyHint": read_only && !may_execute,
            "destructiveHint": !read_only || may_execute,
            "idempotentHint": idempotent,
            "openWorldHint": true
        });
    }
}
